# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-11 02:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='email',
            field=models.EmailField(help_text='The contact email address for the Club.', max_length=254),
        ),
        migrations.AlterField(
            model_name='club',
            name='name',
            field=models.CharField(help_text='Name of the Club.', max_length=50, verbose_name='club'),
        ),
        migrations.AlterField(
            model_name='club',
            name='phone_number',
            field=models.CharField(help_text='The phone number to contact the Club.', max_length=12),
        ),
        migrations.AlterField(
            model_name='club',
            name='president_name',
            field=models.CharField(help_text='The president name of the Club.', max_length=25),
        ),
        migrations.AlterField(
            model_name='club',
            name='year_formed',
            field=models.PositiveIntegerField(help_text='The year the Club was formed.'),
        ),
    ]
