# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-13 06:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_player'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='name',
            new_name='captain_name',
        ),
    ]
