# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-14 12:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20180513_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='club',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='app.Club'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='player',
            name='captain_name',
            field=models.CharField(max_length=25, verbose_name='captain'),
        ),
    ]
